In [1]:
import NetCreator
import networkx as nx
import time
import torch
import os.path as osp
import os

from OperatorEmbedding import get_embedding
import NetCreator 


In [2]:
def generate():
    amount = 100
    t = time.strftime("%Y-%m-%d", time.localtime())
    path = osp.join(os.getcwd(), 'data', 'Logical Plans', 'generated', t) 
    for id in range(amount):
        G = NetCreator.completeNet()['graph']
        nx.write_gpickle(G, path+'_'+str(id))


In [17]:
for _ in range(10):
    G = NetCreator.completeNet()['graph']
    n = G.number_of_nodes()
    e = G.number_of_edges()
    if(not nx.is_weakly_connected(G)):
        print('********')
        break

In [2]:
G = NetCreator.completeNet()['graph']

In [20]:
for n in G.nodes:
    print(G.nodes[n]['platform'].name)

storm
samza
javastream
samza
storm
storm
storm
storm
storm
storm
storm
storm
storm
flink
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm
storm


In [4]:
G.number_of_nodes()

6

In [5]:
G.number_of_edges()

5

In [7]:
for n in G.nodes:
    print(G.nodes[n]['platform'])

In [6]:
for n1, n2, _ in list(G.edges(data=True)):
    print(n1, n2)
    print(G.nodes[n1]['platform'].name)

<operators.Operator object at 0x7f91c3c8b710> <operators.Operator object at 0x7f91c3c8b6d0>
apex
<operators.Operator object at 0x7f91c3c8b6d0> <operators.Operator object at 0x7f91c3c8ba90>
apex
<operators.Operator object at 0x7f91c3c8ba90> <operators.Operator object at 0x7f91c3c8fb10>
apex
<operators.Operator object at 0x7f91c3c8fb10> <operators.Operator object at 0x7f91be019610>
apex


In [30]:
for n in G.nodes:
    print(G.nodes[n]['platform'])

In [22]:
x = [get_embedding(n.name) for n in G.nodes]

In [18]:
x

[array([ 0.01667172, -0.01766417,  0.01586808, -0.02540231,  0.0095831 ,
         0.02662785,  0.00997451, -0.01213459], dtype=float32),
 array([ 0.04816071,  0.00709655, -0.03270233, -0.03643361, -0.0335915 ,
        -0.04006913,  0.06010067,  0.05739323], dtype=float32),
 array([ 0.04919318, -0.01223895, -0.0565662 ,  0.03429526, -0.04614192,
        -0.03805524,  0.04314691,  0.0081333 ], dtype=float32)]

In [19]:
torch.tensor(x, dtype=torch.float)

tensor([[ 0.0167, -0.0177,  0.0159, -0.0254,  0.0096,  0.0266,  0.0100, -0.0121],
        [ 0.0482,  0.0071, -0.0327, -0.0364, -0.0336, -0.0401,  0.0601,  0.0574],
        [ 0.0492, -0.0122, -0.0566,  0.0343, -0.0461, -0.0381,  0.0431,  0.0081]])

In [31]:
from sklearn import preprocessing

In [42]:
le = preprocessing.LabelEncoder()
oe = preprocessing.OneHotEncoder()

In [37]:
import operators, platforms

In [38]:
le.fit([o.name for o in operators.all_opt])

LabelEncoder()

In [41]:
le.transform(['sin','tan'])

array([42, 52])

In [47]:
oe = preprocessing.OneHotEncoder()
oe.fit([[o.name] for o in operators.all_opt])

OneHotEncoder()

In [49]:
oe.transform([['sin']])

<1x61 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>